import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home() {
  const [planets,setPlanets]=useState([])
  const [newPlanet,setNewPlanet]=useState({})
  useEffect(()=>{
    axios.get('http://localhost:8080/Planets').then((res)=>{
      console.log(res.data)
      setPlanets(res.data)
    }).catch((err)=>{
      console.log(err)
    })
  },[newPlanet])

  const handleSubmit = e => {
    e.preventDefault();
    console.log('input data:',e)
    axios.post('http://localhost:8080/Planet',{
      PlanetName:e.target[0].value,
      NumberOfMoon:e.target[1].value,
      LengthOfDay:e.target[2].value
    }).then((res)=>{
      console.log(res.data)
      setNewPlanet(res.data)
    }).catch((err)=>{
      console.log(err)
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Planets App | Homework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Planet.js!</a>
        </h1>

        <p className={styles.description}>
          Your place to inquire about planets {' '}
          <code className={styles.code}>http://PlanetaryPlanetary.com</code>
        </p>

        <div className={styles.grid}>
          {planets.map((e)=>
         { return(
          <div key={e._id}  className={styles.card}>
            <Link href={`/planet/${e._id}`}><h2>{e.PlanetName} &rarr;</h2></Link>
            <p>Press to view this planet</p>
          </div>)}
          )}
        </div>
        <form onSubmit={(e)=>handleSubmit(e)}>
          <input placeholder='Planet name'/>
          <input placeholder='# of Moons' type="number" id="quantity" name="quantity" min="0"/>
          <input placeholder='Day Length in hours' type="number" id="quantity" name="quantity" min="0"/>
          <input type="submit" value="Add a new moon"/>
        </form>
      </main>
    </div>
  )
}
